/*****       Code is generated by a tool.       *****/
CREATE TABLE [LZ_UCI].[Teams] (
    [FIT_DWH_ID] int IDENTITY(1, 1) NOT NULL,
    [Code]    NVARCHAR    NULL,
    [Name]    NVARCHAR    NULL,
    [Team Category]    NVARCHAR    NULL,
    [Country]    NVARCHAR    NULL,
    [Continent]    NVARCHAR    NULL,
    [Format]    NVARCHAR    NULL,
    [Email]    NVARCHAR    NULL,
    [Website]    NVARCHAR    NULL,
)
GO

ALTER TABLE [LZ_UCI].[Teams] ADD PRIMARY KEY([FIT_DWH_ID])
GO
