/*****       Code is generated by a tool.       *****/
CREATE TABLE [UCI].[Teams] (
    [FIT_DWH_ID] int IDENTITY(1, 1) NOT NULL,
    [Code]    NVARCHAR    NULL,
    [Name]    NVARCHAR    NULL,
    [Team Category]    NVARCHAR    NULL,
    [Country]    NVARCHAR    NULL,
    [Continent]    NVARCHAR    NULL,
    [Format]    NVARCHAR    NULL,
    [Email]    NVARCHAR    NULL,
    [Website]    NVARCHAR    NULL,
    [CheckSum_BK] int NULL,
    [CheckSum_AllAttributes] int NULL,
    [InsertDate] datetime null DEFAULT getdate(),
    [UpdateDate] datetime null DEFAULT getdate(),
)
GO

CREATE CLUSTERED COLUMNSTORE INDEX cci_Teams ON [UCI].[Teams]
GO
